# Generated by Django 4.1.7 on 2023-04-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrecord',
            old_name='dete',
            new_name='date',
        ),
    ]
